mapping = {
    "D00": "None",
    "D01": "Augmented I",
    "D02": "Augmented II",
    "D03": "Augmented III",
    "D04": "Augmented IV",
    "D05": "Augmented V",
    "D06": "Augmented VI",
    "D07": "Tattoo I",
    "D08": "Tattoo II",
    "D09": "Tattoo III",
    "D10": "Tattoo IV",
    "D11": "Full Metal I",
    "D12": "Full Metal II",
    "D13": "Tattoo V",
    "D14": "Tattoo VI",
    "D15": "Augmented VII",
    "D16": "Augmented VIII",
    "D17": "Augmented IX",
    "D18": "Augmented X",
    "D19": "Tattoo VII",
    "D20": "Tattoo VIII",
    "D21": "Hybrid I",
    "D22": "Hybrid II",
    "D23": "Hybrid III",
    "D24": "Hybrid IV",
    "D25": "Augmented XI",
    "D26": "Augmented XII",
    "D27": "Hybrid V",
    "D28": "Hybrid VII",
    "D29": "Hybrid VII",
    "D30": "Hybrid VIII",
    "D31": "Augmented XIII",
    "D32": "Augmented XIV",
    "D33": "Augmented XV",
    "D34": "Augmented XVI",
    "D35": "Tattoo IX",
    "D36": "Tattoo X",
    "D37": "Tattoo XI",
    "D38": "Tattoo XII",
    "D39": "Tattoo XIII",
    "D40": "Tattoo XIV"
}