mapping = {
    "D01": "Freeman",
    "D02": "Freeman",
    "D03": "Kharlotte",
    "D04": "Kharlotte",
    "D05": "Runner",
    "D06": "Runner",
    "D07": "Escaper",
    "D08": "Escaper",
    "D09": "Warior",
    "D10": "Warior",
    "D11": "Full Metal",
    "D12": "Full Metal",
    "D13": "Nursing Totem",
    "D14": "Nursing Totem",
    "D15": "Howland",
    "D16": "Howland",
    "D17": "Volya",
    "D18": "Volya",
    "D19": "Paquita",
    "D20": "Paquita",
    "D21": "Pekah",
    "D22": "Pekah",
    "D23": "Siandrah",
    "D24": "Siandrah",
    "D25": "Kika",
    "D26": "Kika",
    "D27": "Frantz",
    "D28": "Frantz",
    "D29": "Franny",
    "D30": "Franny",
    "D31": "Charleen",
    "D32": "Charleen",
    "D33": "Exploerer",
    "D34": "Exploerer",
    "D35": "Protector",
    "D36": "Protector",
    "D37": "Traveler",
    "D38": "Traveler",
    "D39": "Coz-Freedom",
    "D40": "Coz-Freedom"
}