mapping = {
    "E01": "Orange High-Top Chunky Sneakers",
    "E02": "Beige Knit Sneakers",
    "E03": "Gray Knit Sneakers",
    "E04": "Speed Sock Trainers",
    "E05": "Beige Retro Basketball Shoes",
    "E06": "Chelsea Boots",
    "E07": "Sandals",
    "E08": "Roller skates",
    "E09": "Brogue Shoes",
    "E10": "White Canvas Shoes",
    "E11": "Gray Hiking Boots",
    "E12": "Cyber Geta",
    "E13": "Storm-breaker Rain Boots",
    "E14": "Gray Roller Blades",
    "E15": "Blue Roller Blades",
    "E16": "Quilted Sandals",
    "E17": "Furry Slippers",
    "E18": "Ski Boots",
    "E19": "Cozy Hotel Slippers",
    "E20": "Gray Combat Boots",
    "E21": "Gray High-Top Chunky Sneakers",
    "E22": "Gray Retro Basketball Shoes",
    "E23": "Green Canvas Shoes",
    "E24": "Brown Combat Boots",
    "E25": "White Hiking Boots"
}