mapping = {
    "F01": "Short Legging",
    "F02": "Joggers",
    "F03": "Cargo Pants",
    "F04": "Cargo Shorts",
    "F05": "Jogging Shorts",
    "F06": "Jogging Shorts",
    "F07": "Jogging Shorts",
    "F08": "Jean Suspenders",
    "F09": "Jean Suspenders",
    "F10": "Jean Suspenders",
    "F11": "Urban Ankle-tied Pants",
    "F12": "Urban Ankle-tied Pants",
    "F13": "Flare",
    "F14": "Urban Shorts + Girdles",
    "F15": "Urban Shorts + Girdles",
    "F16": "Bermudas",
    "F17": "Skinny Jeans",
    "F18": "Cotton Wadded Trousers + Square Towel",
    "F19": "Cotton Wadded Trousers + Square Towel",
    "F20": "Leggings",
    "F21": "Knitted Skirt",
    "F22": "Jean Shorts",
    "F23": "Jean Shorts",
    "F24": "Culottes",
    "F25": "Culottes",
    "F26": "Culottes",
    "F27": "A-line Skirt",
    "F28": "A-line Skirt",
    "F29": "A-line Skirt",
    "F30": "Pleated Skirt",
    "F31": "Pleated Skirt",
    "F32": "Hiking Pants",
    "F33": "Hiking Pants",
    "F34": "Hiking Pants",
    "F35": "Trousers + Bandage",
    "F36": "Trousers + Bandage",
    "F37": "Wide-leg Pants",
    "F38": "Pyjamas",
    "F39": "Cotton Flares",
    "F40": "Cotton Flares",
    "F41": "Cotton Flares"
}