mapping = {
    "F01": "Cycling Shorts",
    "F02": "Sweatpants",
    "F03": "Nylon Cargo Pants",
    "F04": "Utility Cargo Shorts",
    "F05": "Gray Running Shorts",
    "F06": "Quilted Utility Skirt",
    "F07": "Green Running Shorts",
    "F08": "Green Denim Dungarees",
    "F09": "Blue Denim Dungarees",
    "F10": "Khaki Denim Dungarees",
    "F11": "Dark Gray Tech Trousers",
    "F12": "Utility Cutaway Long Skirt",
    "F13": "Flare Track Pants",
    "F14": "Gray Utility Shorts",
    "F15": "Khaki Utility Shorts",
    "F16": "Denim Bermuda Shorts",
    "F17": "Strap Skinny Trousers",
    "F18": "Gray Bandana Track Pants",
    "F19": "Khaki Bandana Track Pants",
    "F20": "Geo Panel Leggings",
    "F21": "Knit Skirt",
    "F22": "Gray Denim Shorts",
    "F23": "Blue Denim Shorts",
    "F24": "Gray Accessorized Culottes",
    "F25": "Pink Accessorized Culottes",
    "F26": "Blue Accessorized Culottes",
    "F27": "Mix Media Trousers",
    "F28": "Asymmetrical Flare Trousers",
    "F29": "Nomadic Trousers",
    "F30": "Blue Pleated Skirt",
    "F31": "Pink Pleated Skirt",
    "F32": "Beige Hiking Shorts",
    "F33": "Gray Hiking Shorts",
    "F34": "Green Hiking Shorts",
    "F35": "Green Tactical Cargo Pants",
    "F36": "Gray Tactical Cargo Pants",
    "F37": "Ski Shell Pants",
    "F38": "Cozy Pyjamas Pants",
    "F39": "Reflective Nylon Trousers",
    "F40": "Convertible Trousers",
    "F41": "Asymmetrical Cutaway Skirt"
}