mapping = {
    "G01": "Beige Hooded Jacket",
    "G02": "Blue Hooded Jacket",
    "G03": "Green Puffer Vest",
    "G04": "Yellow Puffer Vest",
    "G05": "Blue Puffer Vest",
    "G06": "Rain Coat",
    "G07": "Crop Top",
    "G08": "Long-Sleeve Top",
    "G09": "Sweater Crop Top",
    "G10": "Beige Oversized T-shirt",
    "G11": "White Oversized T-shirt",
    "G12": "Green Oversized T-shirt",
    "G13": "Fleece Jacket",
    "G14": "Blue Bomber Jacket",
    "G15": "Green Bomber Jacket",
    "G16": "Red Bomber Jacket",
    "G17": "Parka Jacket",
    "G18": "Blue Flannel Jacket",
    "G19": "Navy Blue Flannel Jacket",
    "G20": "Yellow Flannel Jacket",
    "G21": "Windbreaker",
    "G22": "Red Crop Top",
    "G23": "Blue Crop Top",
    "G24": "Beige Puffer Jacket",
    "G25": "Gray Puffer Jacket",
    "G26": "Blue Puffer Jacket",
    "G27": "Hooded Denim Jacket",
    "G28": "Hooded Denim Jacket",
    "G29": "Brown Knitted Sweater",
    "G30": "Blue Knitted Sweater",
    "G31": "Green Knitted Sweater",
    "G32": "Ripped Tank Top",
    "G33": "Formal Shirt",
    "G34": "Red Athletic Long Sleeve",
    "G35": "White Athletic Long Sleeve",
    "G36": "Gray Athletic Long Sleeve",
    "G37": "Short Blouse",
    "G38": "Short Blouse",
    "G39": "Short Blouse",
    "G40": "Camo Jacket",
    "G41": "Gray Long Sleeve Sweatshirt",
    "G42": "White Long Sleeve Sweatshirt",
    "G43": "Green Pattern Print T-shirt",
    "G44": "Blue Pattern Print T-shirt",
    "G45": "Tie Dye Tee",
    "G46": "Varisity Jacket",
    "G47": "Bath Robe"
}