mapping = {
    "G01": "Beige Sherpa Jacket",
    "G02": "Blue Sherpa Jacket",
    "G03": "Green Puffer Vest",
    "G04": "Two-tone Puffer Vest",
    "G05": "Blue Puffer Vest",
    "G06": "White Rain Coat",
    "G07": "Blue Cropped T-shirt",
    "G08": "Long Sleeve T-shirt",
    "G09": "Quilted Vest",
    "G10": "Beige Utility T-shirt",
    "G11": "Blue Utility T-shirt",
    "G12": "Green Utility T-shirt",
    "G13": "Multicolor Fleece Jacket",
    "G14": "Blue Bomber Jacket",
    "G15": "Green Bomber Jacket",
    "G16": "Red Bomber Jacket",
    "G17": "Multicolor Shell Parka Jacket",
    "G18": "Blue Flannel Jacket",
    "G19": "Navy Flannel Jacket",
    "G20": "Yellow Flannel Jacket",
    "G21": "Multicolor Windbreaker Jacket",
    "G22": "Red Cropped Top",
    "G23": "Blue Cropped Top",
    "G24": "Beige Down Jacket",
    "G25": "Gray Down Jacket",
    "G26": "Blue Down Jacket",
    "G27": "Blue Hooded Denim Jacket",
    "G28": "Khaki Hooded Denim Jacket",
    "G29": "Tan Fair Isle Sweater",
    "G30": "Blue Fair Isle Sweater",
    "G31": "Green Native Sweater",
    "G32": "Ripped Tank Top",
    "G33": "Dress Shirt",
    "G34": "Red Cropped Sweatshirt",
    "G35": "White Cropped Sweatshirt",
    "G36": "Gray Cropped Sweatshirt",
    "G37": "White Nylon Shirt",
    "G38": "Blue Nylon Shirt",
    "G39": "Khaki Nylon Shirt",
    "G40": "Camo Field Jacket",
    "G41": "Gray Crewneck Sweatshirt",
    "G42": "White Crewneck Sweatshirt",
    "G43": "Mixed Pattern Shirt",
    "G44": "Geometric Pattern Shirt",
    "G45": "Tie Dye T-shirt",
    "G46": "Cozy Varisity Jacket",
    "G47": "Bathrobe",
    "G48": "Mixed Media Windbreaker",
    "G49": "Neon Full-Zip Cardigan",
    "G50": "Padded Cropped Vest",
    "G51": "Oversized Shirt Jacket",
    "G52": "Multicolor Quilted Down Jacket",
    "G53": "Gray Cold Shoulder Sweater",
    "G54": "Pink Cold Shoulder Sweater"
}