mapping = {
    "H01": "Tech Panel",
    "H02": "Nutrient Bottle",
    "H03": "Nignt Vision",
    "H04": "Pizza Protector",
    "H05": "Travel Kettle",
    "H06": "Goldfish Kinetic Energy Converter",
    "H07": "Carolien",
    "H08": "Mid Night Crystal Lantern",
    "H09": "Gas Mask",
    "H10": "Bluetooth Speaker",
    "H11": "Longboard",
    "H12": "Floating Hoverboard",
    "H13": "Novel",
    "H14": "Bear Bear Lollipop",
    "H15": "Bubble Tea",
    "H16": "Pipe",
    "H17": "Bouquet",
    "H18": "Boxing Gloves",
    "H19": "Kendama",
    "H20": "Magic Egg Protection Basket",
    "H21": "Spray Paint",
    "H22": "First Aid Bottle",
    "H23": "Yo-Yo",
    "H24": "Fan",
    "H25": "Beer",
    "H26": "Gamepad",
    "H27": "Hover Board",
    "H28": "Tamagotchi",
    "H29": "Potato Chips",
    "H30": "Instant Camera",
    "H31": "Instant Photo",
    "H32": "Handheld",
    "H33": "Flip Handheld",
    "H34": "Palette",
    "H35": "Art-drawing Paper",
    "H36": "Instant Noodles",
    "H37": "Lemon Juice",
    "H38": "Vape"
}