mapping = {
    "H00": "None",
    "H01": "Tech Panel",
    "H02": "Nutrient Bottle",
    "H03": "Night Vision Goggles",
    "H04": "Pizza Protector",
    "H05": "Bottle",
    "H06": "Goldfish Energy Converter",
    "H07": "Tutu",
    "H08": "Crystal Lantern",
    "H09": "Gas Mask",
    "H10": "Bluetooth Speaker",
    "H11": "Longboard",
    "H12": "Umbrella",
    "H13": "Journal",
    "H14": "Bear Bear Lollipop",
    "H15": "Bubble Tea",
    "H16": "Pipe",
    "H17": "Bouquet",
    "H18": "Boxing Gloves",
    "H19": "Kendama",
    "H20": "Magic Egg",
    "H21": "Spray Paint",
    "H22": "First Aid Bottle",
    "H23": "Yo-Yo",
    "H24": "Fan",
    "H25": "Beer",
    "H26": "Gamepad",
    "H27": "Hover Board",
    "H28": "Tamagotchi",
    "H29": "Potato Chips",
    "H30": "Polaroid",
    "H31": "Polaroid Film",
    "H32": "Vape",
    "H33": "Portable Gaming Console",
    "H34": "Palette",
    "H35": "Papers",
    "H36": "Instant Noodles",
    "H37": "Lemon Juice"
}