mapping = {
    "I00": "None",
    "I01": "Jetpack",
    "I02": "Flower Protector",
    "I03": "Bionic Gliding Jetpack",
    "I04": "Pizza Delivery Box",
    "I05": "Goldfish Express Bag",
    "I06": "Nutrient Solution Shoulder Pack",
    "I07": "Bonsai Oxygen Provider",
    "I08": "New Hope Protector",
    "I09": "Green First-Aid Kit",
    "I10": "Pink First-Aid Kit",
    "I11": "Gray First-Aid Kit",
    "I12": "Oxygen Backpack",
    "I13": "Green Travel Bag",
    "I14": "Beige Travel Bag",
    "I15": "Blue Travel Bag",
    "I16": "Tech Bass",
    "I17": "Tech Scroll Holder",
    "I18": "Crossbody Bag",
    "I19": "Brown Messenger Bag",
    "I20": "Gray Messenger Bag",
    "I21": "Heart Guitar",
    "I22": "Dangerous Elements Bag",
    "I23": "Urban Bag",
    "I24": "Electronic Keyboard",
    "I25": "Khaki Strap Bag",
    "I26": "Green Strap Bag",
    "I27": "Eth Bag",
    "I28": "Green Camping Bag",
    "I29": "Blue Camping Bag",
    "I30": "Orange Shoulder Bag",
    "I31": "Square Bag",
    "I32": "Speaker Bag",
    "I33": "Pepe Guitar",
    "I34": "Mushroom Terrarium"
}