mapping = {
    "I01": "Jetpack",
    "I02": "Flower Protector",
    "I03": "Bionic Gliding Jetpack",
    "I04": "Pizza Delivery Box",
    "I05": "Goldfish Express Backpack",
    "I06": "Nutrient Solution Shoulder Pack",
    "I07": "Bonsai Oxygen Provider",
    "I08": "New Hope Protector",
    "I09": "First-aid Kit",
    "I10": "First-aid Kit",
    "I11": "First-aid Kit",
    "I12": "Oxygen Backpack",
    "I13": "Traveling Backpack",
    "I14": "Traveling Backpack",
    "I15": "Traveling Backpack",
    "I16": "Tech Bass",
    "I17": "Tech Scroll Holder",
    "I18": "Crossbody Bag",
    "I19": "Messenger Bag",
    "I20": "Messenger Bag",
    "I21": "Heart Shape Guitar",
    "I22": "Dangerous Elements Backpack",
    "I23": "Urban Roll Top Pack",
    "I24": "Electronic Keyboard",
    "I25": "Strap Backpack",
    "I26": "Strap Backpack",
    "I27": "Ethereum Backpack",
    "I28": "Camping Bag",
    "I29": "Camping Bag",
    "I30": "Shoulder Bag",
    "I31": "Square Backpack",
    "I32": "Speaker Backpack",
    "I33": "Pepe Guitar"
}