mapping = {
    "J01": "Blunt Short Cut",
    "J02": "Blunt Short Cut",
    "J03": "Blunt Short Cut",
    "J04": "Buzz Cut",
    "J05": "Buzz Cut",
    "J06": "Low Double Bun",
    "J07": "Low Double Bun",
    "J08": "Low Double Bun",
    "J09": "Man Bun",
    "J10": "Man Bun",
    "J11": "French Braids",
    "J12": "French Braids",
    "J13": "French Braids",
    "J14": "Wavy Hair with Design Fade",
    "J15": "Wavy Hair with Design Fade",
    "J16": "Simple Hair with Design Fade",
    "J17": "Simple Hair with Design Fade",
    "J18": "Low Bun",
    "J19": "Low Bun",
    "J20": "Low Bun",
    "J21": "Wolf Cut",
    "J22": "Wolf Cut",
    "J23": "Wolf Cut",
    "J24": "Wolf Cut",
    "J25": "Wolf Cut",
    "J26": "Bob",
    "J27": "Bob",
    "J28": "Bob",
    "J29": "Brushed Up",
    "J30": "Brushed Up",
    "J31": "Short Half-ponytail",
    "J32": "Short Half-ponytail",
    "J33": "Short Half-ponytail",
    "J34": "Short Half-ponytail",
    "J35": "Short Half-ponytail",
    "J36": "Long Curly Hair",
    "J37": "Long Curly Hair",
    "J38": "Long Curly Hair",
    "J39": "Curly Short",
    "J40": "Curly Short",
    "J41": "Long Straight Hair",
    "J42": "Long Straight Hair",
    "J43": "Long Straight Hair",
    "J44": "Long Straight Hair",
    "J45": "Long Straight Hair",
    "J46": "Short Pigtails",
    "J47": "Short Pigtails",
    "J48": "Short Pigtails",
    "J49": "Short Pigtails",
    "J50": "Midlong Hair",
    "J51": "Midlong Hair",
    "J52": "Midlong Hair",
    "J53": "Midlong Hair",
    "J54": "Afro",
    "J55": "Afro",
    "J56": "Pixie",
    "J57": "Pixie",
    "J58": "Pixie",
    "J59": "Pixie",
    "J60": "Pixie",
    "J61": "French Crop",
    "J62": "French Crop",
    "J63": "French Crop",
    "J64": "French Crop",
    "J65": "Dread & Braids",
    "J66": "Dread & Braids",
    "J67": "Dread & Braids",
}