mapping = {
    "J01": "Brown Blunt Short Cut",
    "J02": "Gray Blunt Short Cut",
    "J03": "Blue Blunt Short Cut",
    "J04": "Brown Buzz Cut",
    "J05": "Gray Buzz Cut",
    "J06": "Pink Low Double Bun",
    "J07": "Gray Low Double Bun",
    "J08": "Brown Low Double Bun",
    "J09": "Brown Man Bun",
    "J10": "Gray Man Bun",
    "J11": "Orange French Braids",
    "J12": "Blue French Braids",
    "J13": "White French Braids",
    "J14": "Brown Wavy Hair with Design Fade",
    "J15": "Gray Wavy Hair with Design Fade",
    "J16": "Brown Simple Hair with Design Fade",
    "J17": "Gray Simple Hair with Design Fade",
    "J18": "White Low Bun",
    "J19": "Gray Low Bun",
    "J20": "Yellow Low Bun",
    "J21": "Blue Wolf Cut",
    "J22": "Brown Wolf Cut",
    "J23": "Green Wolf Cut",
    "J24": "Gray Wolf Cut",
    "J25": "Pink Wolf Cut",
    "J26": "Gray Bob Cut",
    "J27": "Green Bob Cut",
    "J28": "Yellow Bob Cut",
    "J29": "Yellow Brushed Up",
    "J30": "Gray Brushed Up",
    "J31": "Light Gray Short Half-ponytail",
    "J32": "Gray Short Half-ponytail",
    "J33": "Pink Short Half-ponytail",
    "J34": "Yellow Short Half-ponytail",
    "J35": "Green Short Half-ponytail",
    "J36": "Yellow Long Curly Hair",
    "J37": "Brown Long Curly Hair",
    "J38": "Blue Long Curly Hair",
    "J39": "White Curly Short",
    "J40": "Brown Curly Short",
    "J41": "Yellow Long Straight Hair",
    "J42": "Blue Long Straight Hair",
    "J43": "Pink Long Straight Hair",
    "J44": "Gray Long Straight Hair",
    "J45": "Brown Long Straight Hair",
    "J46": "Orange Short Pigtails",
    "J47": "Blue Short Pigtails",
    "J48": "Green Short Pigtails",
    "J49": "Gray Short Pigtails",
    "J50": "Gray Mid Long Hair",
    "J51": "Yellow Mid Long Hair",
    "J52": "Brown Mid Long Hair",
    "J53": "Blue Mid Long Hair",
    "J54": "Brown Afro",
    "J55": "Gray Afro",
    "J56": "Blue Pixie Cut",
    "J57": "Yellow Pixie Cut",
    "J58": "Pink Pixie Cut",
    "J59": "White Pixie Cut",
    "J60": "Gray Pixie Cut",
    "J61": "Green French Crop",
    "J62": "Gray French Crop",
    "J63": "Blue French Crop",
    "J64": "Orange French Crop",
    "J65": "Orange Dread & Braids",
    "J66": "Brown Dread & Braids",
    "J67": "Gray Dread & Braids",
    "J68": "Black Mohawk",
    "J69": "White Mohawk",
    "J70": "Bald",
}