mapping = {
    "K01": "Drone3",
    "K02": "Double Ear Robot",
    "K03": "Binaural Ball Robot",
    "K04": "Bionic Jelly Fish Light Bot",
    "K05": "DroneX",
    "K06": "Nutrient Solution Drone",
    "K07": "Bionic Drone Whale",
    "K08": "Broadcast Drone",
    "K09": "News Rocket",
    "K10": "Automatic Nutrient Supplier",
    "K11": "Chick Robot",
    "K12": "Tech Arms Chamberlain",
    "K13": "Round Bee Robot",
    "K14": "Floating Projector",
    "K15": "Goldfish Robot",
    "K16": "UFO",
    "K17": "Guiding Principle",
    "K18": "Hamburger Robot",
    "K19": "Advertising Transmitter",
    "K20": "Bionic Bird",
    "K21": "Round Jet"
}