mapping = {
    "L00": "None",
    "L01": "Orange Aviator Hat",
    "L02": "Blue Aviator Hat",
    "L03": "Gray Aviator Hat",
    "L04": "Green Fisherman Beanie",
    "L05": "Purple Fisherman Beanie",
    "L06": "Red Fisherman Beanie",
    "L07": "Purple Kitty Cat Headphone",
    "L08": "Orange Kitty Cat Headphone",
    "L09": "Pink Plant on Head",
    "L10": "Yellow Plant on Head",
    "L11": "Aviator Goggles",
    "L12": "Pink Cyber Kitsune Mask",
    "L13": "Beige Cyber Kitsune Mask",
    "L14": "Cyber Halo",
    "L15": "Fedora Hat",
    "L16": "Synthetic Antenna",
    "L17": "Nurse Cap",
    "L18": "Bear Ears Headband",
    "L19": "Rubber Ducky Transmitter",
    "L20": "Headphones",
    "L21": "Gray 5-panel Cap",
    "L22": "Khaki 5-panel Cap",
    "L23": "Blue 5-panel Cap",
    "L24": "Outcast Bandana",
    "L25": "Red Bear Mask",
    "L26": "Orange Bear Mask",
    "L27": "Rebel Headband",
    "L28": "Tech Helmet",
    "L29": "Cat-Eye Sunglasses",
    "L30": "Green Bucket Hat",
    "L31": "Gray Bucket Hat",
    "L32": "Tie Dye Bucket Hat",
    "L33": "Flat Cap",
    "L34": "Antlers",
    "L35": "Green Beanie",
    "L36": "White Beanie",
    "L37": "Red Pom Pom Beanie",
    "L38": "Pink Bunny Mask",
    "L39": "Blue Bunny Mask",
    "L40": "Coffee Mug",
    "L41": "Soda Helmet",
    "L42": "Blue EMF Protector",
    "L43": "Pink EMF Protector",
    "L44": "Black King Chess Piece",
    "L45": "Furry Bucket Hat",
    "L46": "White Feather",
    "L47": "Black Feather",
    "L48": "Blue Bunny Cap",
    "L49": "Pink Bunny Cap",
    "L50": "Yellow Bunny Cap",
    "L51": "White King Chess Piece"
}