mapping = {
    "L01": "Pilot Hat",
    "L02": "Pilot Hat",
    "L03": "Pilot Hat",
    "L04": "Knit Sailor Cap",
    "L05": "Knit Sailor Cap",
    "L06": "Knit Sailor Cap",
    "L07": "Kitty Cat Headphone",
    "L08": "Kitty Cat Headphone",
    "L09": "Plant on Head",
    "L10": "Plant on Head",
    "L11": "Adventure Goggles",
    "L12": "High Tech Foxy Mask",
    "L13": "High Tech Foxy Mask",
    "L14": "Heat Protect Halo",
    "L15": "Fedora Hat",
    "L16": "Synthetic Antenna",
    "L17": "Nurse Cap",
    "L18": "Bear Headband",
    "L19": "Ducky Transmitter",
    "L20": "Headphone",
    "L21": "5-panel Cap",
    "L22": "5-panel Cap",
    "L23": "5-panel Cap",
    "L24": "Rebellious Scarf",
    "L25": "Bear Mask",
    "L26": "Bear Mask",
    "L27": "Swoosh Headband",
    "L28": "Trend Feather",
    "L29": "Sunglasses",
    "L30": "Bucket Hat",
    "L31": "Bucket Hat",
    "L32": "Bucket Hat",
    "L33": "Beret",
    "L34": "Antlers",
    "L35": "Beanie",
    "L36": "Beanie",
    "L37": "Beanie",
    "L38": "Bunny Mask",
    "L39": "Bunny Mask",
    "L40": "Coffee Cup",
    "L41": "Soda Cap",
    "L42": "Radio Wave Protective Helmet",
    "L43": "Radio Wave Protective Helmet",
    "L44": "Radio Wave Protective Helmet",
    "L45": "Fluffy Hat",
    "L46": "Tech Helmet",
    "L47": "Bunny Cap",
    "L48": "Bunny Cap",
    "L49": "Bunny Cap",
    "L50": "Chess"
}